export interface UtilityOpenApiServerOptions {
    host: string;
    port: number;
}

export function BuildUtilityOpenApiSpecification(
    options: UtilityOpenApiServerOptions,
): Record<string, unknown> {
    const baseUrl = `http://${options.host}:${options.port}`;

    return {
        openapi: "3.1.0",
        info: {
            title: "Strategies Utility Billing API",
            version: "1.0.0",
            description:
                "Reusable electric utility billing API for customer accounts, interval metering, invoicing, payments, idempotency, and overdue assessments.",
            contact: {
                name: "Strategies Maintainers",
                url: "https://github.com",
            },
            license: {
                name: "MIT",
            },
        },
        servers: [
            {
                url: baseUrl,
            },
        ],
        tags: [
            { name: "Health" },
            { name: "Customers" },
            { name: "Tariffs" },
            { name: "Billing Cycles" },
            { name: "Meter Readings" },
            { name: "Billing" },
            { name: "Invoices" },
            { name: "Payments" },
            { name: "Operations" },
        ],
        components: {
            headers: {
                RequestId: {
                    description:
                        "Request correlation identifier. Echoes X-Request-Id from request or auto-generated by server.",
                    schema: {
                        type: "string",
                    },
                },
                IdempotencyKey: {
                    description:
                        "Idempotency key for safely replaying billing and payment requests.",
                    schema: {
                        type: "string",
                    },
                },
            },
            schemas: {
                ErrorResponse: {
                    type: "object",
                    additionalProperties: false,
                    properties: {
                        code: { type: "string" },
                        error: { type: "string" },
                        requestId: { type: "string" },
                    },
                    required: ["code", "error", "requestId"],
                },
                HealthResponse: {
                    type: "object",
                    additionalProperties: false,
                    properties: {
                        status: { type: "string", enum: ["ok"] },
                    },
                    required: ["status"],
                },
                ServiceAddress: {
                    type: "object",
                    additionalProperties: false,
                    properties: {
                        line1: { type: "string" },
                        line2: { type: "string" },
                        city: { type: "string" },
                        region: { type: "string" },
                        postalCode: { type: "string" },
                        country: { type: "string" },
                    },
                    required: ["line1", "city", "region", "postalCode", "country"],
                },
                CustomerAccount: {
                    type: "object",
                    properties: {
                        id: { type: "string" },
                        accountNumber: { type: "string" },
                        externalId: { type: "string" },
                        fullName: { type: "string" },
                        email: { type: "string" },
                        phone: { type: "string" },
                        deviceId: { type: "string" },
                        notificationChannels: {
                            type: "array",
                            items: { type: "string" },
                        },
                        status: {
                            type: "string",
                            enum: ["Active", "Inactive", "Suspended", "Disconnected"],
                        },
                        serviceAddress: { $ref: "#/components/schemas/ServiceAddress" },
                        billingAddress: { $ref: "#/components/schemas/ServiceAddress" },
                    },
                    required: [
                        "id",
                        "accountNumber",
                        "externalId",
                        "fullName",
                        "email",
                        "phone",
                        "deviceId",
                        "notificationChannels",
                        "status",
                        "serviceAddress",
                        "billingAddress",
                    ],
                },
                TariffPlan: {
                    type: "object",
                    properties: {
                        id: { type: "string" },
                        name: { type: "string" },
                        currency: { type: "string" },
                        baseRatePerKwh: { type: "number" },
                        fixedCharge: { type: "number" },
                        weekendDiscountRate: { type: "number" },
                        regulatoryChargePerKwh: { type: "number" },
                        taxRate: { type: "number" },
                        peakWindows: {
                            type: "array",
                            items: {
                                type: "object",
                                properties: {
                                    startHour: { type: "number" },
                                    endHour: { type: "number" },
                                    multiplier: { type: "number" },
                                    daysOfWeek: {
                                        type: "array",
                                        items: { type: "number" },
                                    },
                                },
                                required: ["startHour", "endHour", "multiplier"],
                            },
                        },
                    },
                    required: [
                        "id",
                        "name",
                        "currency",
                        "baseRatePerKwh",
                        "fixedCharge",
                        "weekendDiscountRate",
                        "regulatoryChargePerKwh",
                        "taxRate",
                        "peakWindows",
                    ],
                },
                BillingCycle: {
                    type: "object",
                    properties: {
                        id: { type: "string" },
                        customerId: { type: "string" },
                        startsAt: { type: "string", format: "date-time" },
                        endsAt: { type: "string", format: "date-time" },
                        dueAt: { type: "string", format: "date-time" },
                        status: {
                            type: "string",
                            enum: [
                                "Open",
                                "Closed",
                                "Issued",
                                "PartiallyPaid",
                                "Paid",
                                "Overdue",
                            ],
                        },
                    },
                    required: ["id", "customerId", "startsAt", "endsAt", "dueAt", "status"],
                },
                MeterReadingBatch: {
                    type: "object",
                    properties: {
                        meterId: { type: "string" },
                        customerId: { type: "string" },
                        timezone: { type: "string" },
                        intervals: {
                            type: "array",
                            items: {
                                type: "object",
                                properties: {
                                    startedAt: { type: "string", format: "date-time" },
                                    endedAt: { type: "string", format: "date-time" },
                                    consumedKwh: { type: "number" },
                                },
                                required: ["startedAt", "endedAt", "consumedKwh"],
                            },
                        },
                    },
                    required: ["meterId", "customerId", "timezone", "intervals"],
                },
                PaymentRequest: {
                    type: "object",
                    properties: {
                        invoiceId: { type: "string" },
                        amount: { type: "number" },
                        method: {
                            type: "string",
                            enum: ["Card", "BankTransfer", "Cash", "Wallet"],
                        },
                        reference: { type: "string" },
                        idempotencyKey: { type: "string" },
                    },
                    required: ["invoiceId", "amount", "method"],
                },
                LateFeePolicy: {
                    type: "object",
                    properties: {
                        graceDays: { type: "number" },
                        dailyRate: { type: "number" },
                        fixedFee: { type: "number" },
                        maximumFee: { type: "number" },
                    },
                    required: ["graceDays", "dailyRate", "fixedFee"],
                },
            },
        },
        paths: {
            "/health": {
                get: {
                    tags: ["Health"],
                    summary: "Service health status",
                    responses: {
                        "200": {
                            description: "Service is healthy",
                            headers: {
                                "x-request-id": {
                                    $ref: "#/components/headers/RequestId",
                                },
                            },
                            content: {
                                "application/json": {
                                    schema: {
                                        $ref: "#/components/schemas/HealthResponse",
                                    },
                                },
                            },
                        },
                    },
                },
            },
            "/openapi.json": {
                get: {
                    tags: ["Operations"],
                    summary: "Fetch OpenAPI specification",
                    responses: {
                        "200": {
                            description: "OpenAPI specification",
                            headers: {
                                "x-request-id": {
                                    $ref: "#/components/headers/RequestId",
                                },
                            },
                        },
                    },
                },
            },
            "/customers": {
                post: {
                    tags: ["Customers"],
                    summary: "Create or update a customer account",
                    requestBody: {
                        required: true,
                        content: {
                            "application/json": {
                                schema: {
                                    $ref: "#/components/schemas/CustomerAccount",
                                },
                            },
                        },
                    },
                    responses: {
                        "201": {
                            description: "Customer account persisted",
                            headers: {
                                "x-request-id": {
                                    $ref: "#/components/headers/RequestId",
                                },
                            },
                        },
                        "400": {
                            description: "Validation error",
                            content: {
                                "application/json": {
                                    schema: {
                                        $ref: "#/components/schemas/ErrorResponse",
                                    },
                                },
                            },
                        },
                    },
                },
                get: {
                    tags: ["Customers"],
                    summary: "List customer accounts",
                    responses: {
                        "200": {
                            description: "Customers list",
                            headers: {
                                "x-request-id": {
                                    $ref: "#/components/headers/RequestId",
                                },
                            },
                        },
                    },
                },
            },
            "/customers/{customerId}": {
                get: {
                    tags: ["Customers"],
                    summary: "Get customer account by id",
                    parameters: [
                        {
                            name: "customerId",
                            in: "path",
                            required: true,
                            schema: { type: "string" },
                        },
                    ],
                    responses: {
                        "200": {
                            description: "Customer account",
                            headers: {
                                "x-request-id": {
                                    $ref: "#/components/headers/RequestId",
                                },
                            },
                        },
                        "404": {
                            description: "Customer not found",
                            content: {
                                "application/json": {
                                    schema: {
                                        $ref: "#/components/schemas/ErrorResponse",
                                    },
                                },
                            },
                        },
                    },
                },
            },
            "/tariff-plans": {
                post: {
                    tags: ["Tariffs"],
                    summary: "Create or update tariff plan",
                    requestBody: {
                        required: true,
                        content: {
                            "application/json": {
                                schema: { $ref: "#/components/schemas/TariffPlan" },
                            },
                        },
                    },
                    responses: {
                        "201": {
                            description: "Tariff plan persisted",
                            headers: {
                                "x-request-id": {
                                    $ref: "#/components/headers/RequestId",
                                },
                            },
                        },
                    },
                },
                get: {
                    tags: ["Tariffs"],
                    summary: "List tariff plans",
                    responses: {
                        "200": {
                            description: "Tariffs list",
                            headers: {
                                "x-request-id": {
                                    $ref: "#/components/headers/RequestId",
                                },
                            },
                        },
                    },
                },
            },
            "/billing-cycles": {
                post: {
                    tags: ["Billing Cycles"],
                    summary: "Create billing cycle",
                    requestBody: {
                        required: true,
                        content: {
                            "application/json": {
                                schema: {
                                    $ref: "#/components/schemas/BillingCycle",
                                },
                            },
                        },
                    },
                    responses: {
                        "201": {
                            description: "Billing cycle persisted",
                            headers: {
                                "x-request-id": {
                                    $ref: "#/components/headers/RequestId",
                                },
                            },
                        },
                    },
                },
                get: {
                    tags: ["Billing Cycles"],
                    summary: "List billing cycles by customer",
                    parameters: [
                        {
                            name: "customerId",
                            in: "query",
                            required: true,
                            schema: { type: "string" },
                        },
                    ],
                    responses: {
                        "200": {
                            description: "Billing cycles list",
                            headers: {
                                "x-request-id": {
                                    $ref: "#/components/headers/RequestId",
                                },
                            },
                        },
                    },
                },
            },
            "/meter-readings": {
                post: {
                    tags: ["Meter Readings"],
                    summary: "Store interval meter readings",
                    requestBody: {
                        required: true,
                        content: {
                            "application/json": {
                                schema: {
                                    $ref: "#/components/schemas/MeterReadingBatch",
                                },
                            },
                        },
                    },
                    responses: {
                        "201": {
                            description: "Readings stored",
                            headers: {
                                "x-request-id": {
                                    $ref: "#/components/headers/RequestId",
                                },
                            },
                        },
                    },
                },
            },
            "/billing-runs": {
                post: {
                    tags: ["Billing"],
                    summary: "Generate invoice from meter intervals",
                    parameters: [
                        {
                            name: "Idempotency-Key",
                            in: "header",
                            required: false,
                            schema: { type: "string" },
                        },
                    ],
                    responses: {
                        "201": {
                            description: "Invoice generated",
                            headers: {
                                "x-request-id": {
                                    $ref: "#/components/headers/RequestId",
                                },
                                "idempotency-key": {
                                    $ref: "#/components/headers/IdempotencyKey",
                                },
                            },
                        },
                        "409": {
                            description: "Idempotency key conflict",
                            content: {
                                "application/json": {
                                    schema: {
                                        $ref: "#/components/schemas/ErrorResponse",
                                    },
                                },
                            },
                        },
                    },
                },
            },
            "/invoices": {
                get: {
                    tags: ["Invoices"],
                    summary: "List invoices by customer",
                    parameters: [
                        {
                            name: "customerId",
                            in: "query",
                            required: true,
                            schema: { type: "string" },
                        },
                    ],
                    responses: {
                        "200": {
                            description: "Invoices list",
                            headers: {
                                "x-request-id": {
                                    $ref: "#/components/headers/RequestId",
                                },
                            },
                        },
                    },
                },
            },
            "/invoices/{invoiceId}": {
                get: {
                    tags: ["Invoices"],
                    summary: "Get invoice by id",
                    parameters: [
                        {
                            name: "invoiceId",
                            in: "path",
                            required: true,
                            schema: { type: "string" },
                        },
                    ],
                    responses: {
                        "200": {
                            description: "Invoice detail",
                            headers: {
                                "x-request-id": {
                                    $ref: "#/components/headers/RequestId",
                                },
                            },
                        },
                        "404": {
                            description: "Invoice not found",
                            content: {
                                "application/json": {
                                    schema: {
                                        $ref: "#/components/schemas/ErrorResponse",
                                    },
                                },
                            },
                        },
                    },
                },
            },
            "/invoices/{invoiceId}/overdue-assessments": {
                post: {
                    tags: ["Invoices"],
                    summary: "Assess overdue late fee for an invoice",
                    parameters: [
                        {
                            name: "invoiceId",
                            in: "path",
                            required: true,
                            schema: { type: "string" },
                        },
                    ],
                    requestBody: {
                        required: true,
                        content: {
                            "application/json": {
                                schema: {
                                    type: "object",
                                    properties: {
                                        asOf: {
                                            type: "string",
                                            format: "date-time",
                                        },
                                        policy: {
                                            $ref: "#/components/schemas/LateFeePolicy",
                                        },
                                    },
                                    required: ["policy"],
                                },
                            },
                        },
                    },
                    responses: {
                        "200": {
                            description: "Overdue assessment applied",
                            headers: {
                                "x-request-id": {
                                    $ref: "#/components/headers/RequestId",
                                },
                            },
                        },
                    },
                },
            },
            "/payments": {
                post: {
                    tags: ["Payments"],
                    summary: "Apply payment to invoice",
                    parameters: [
                        {
                            name: "Idempotency-Key",
                            in: "header",
                            required: false,
                            schema: { type: "string" },
                        },
                    ],
                    requestBody: {
                        required: true,
                        content: {
                            "application/json": {
                                schema: {
                                    $ref: "#/components/schemas/PaymentRequest",
                                },
                            },
                        },
                    },
                    responses: {
                        "201": {
                            description: "Payment processed",
                            headers: {
                                "x-request-id": {
                                    $ref: "#/components/headers/RequestId",
                                },
                                "idempotency-key": {
                                    $ref: "#/components/headers/IdempotencyKey",
                                },
                            },
                        },
                        "409": {
                            description: "Idempotency key conflict",
                            content: {
                                "application/json": {
                                    schema: {
                                        $ref: "#/components/schemas/ErrorResponse",
                                    },
                                },
                            },
                        },
                    },
                },
                get: {
                    tags: ["Payments"],
                    summary: "List payments by invoice",
                    parameters: [
                        {
                            name: "invoiceId",
                            in: "query",
                            required: true,
                            schema: { type: "string" },
                        },
                    ],
                    responses: {
                        "200": {
                            description: "Payments list",
                            headers: {
                                "x-request-id": {
                                    $ref: "#/components/headers/RequestId",
                                },
                            },
                        },
                    },
                },
            },
        },
    };
}
